---
- yum:
    name: MySQL-python
    state: present
- service:
    name: mariadb
    state: started
    
- mysql_user:
    name: "{{database_username}}"
    password: "{{database_password}}"
    priv: '*.*:ALL'
    state: present
- name: "Create db"
  mysql_db:
    name: "{{database_name}}"
    state: present